[package]
name = "plugify-plugin-rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
plugify = { git = "https://github.com/untrustedmodders/rust-plugify", tag = "plugify-v1.2.1" }

[features]
verbose = []